### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tdmalone** [neonadventures/slack-docker-hub-integration#10]
At the moment, the code in this repo is technically “all rights reserved”, although I’m guessing that wasn’t your intention since the repo is public.

Are you open to adding an open source license, to give clarity to people seeking to use (and build on) this code?

I’d be happy to send a suitable license in a pull request.

**Comment by redroot** [comment]
Yep that sounds good to me, I'll be expecting your PR, thanks for doing that 👍

**Comment by tdmalone** [comment]
@redroot You're not a contributor on this repo though? :/

**Comment by redroot** [comment]
@tdmalone true but I'm on the team, and @andykent (team member and contributor) has requested I handle this on his behalf.

**Comment by redroot** [comment]
Also this repo may not be defunct in any case https://docs.docker.com/docker-cloud/slack-integration/

**Comment by tdmalone** [comment]
Ah, true. I'm interested in the license because I've built on this for [another Slack integration](https://github.com/tdmalone/statuspage-to-slack), using it as an opportunity to start learning Ruby. So I was keen to ensure that what I had built from was an open license :)
